//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryParseSteam
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_LIST
    {
        public int GL_ID { get; set; }
        public string GL_NAME { get; set; }
        public string GL_IMAGE_PATH { get; set; }
        public double GL_PRICE { get; set; }
        public Nullable<bool> GL_AVAILABILITY { get; set; }
        public Nullable<double> GL_PRICE_RU { get; set; }
        public Nullable<double> GL_PRICE_KZ { get; set; }
        public Nullable<double> GL_PRICE_TR { get; set; }
        public Nullable<int> GL_STEAM_ID { get; set; }
        public Nullable<int> GL_STEAM_BUNDLE_ID { get; set; }
        public string GL_STEAM_REF { get; set; }
    }
}
