//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryParseSteam
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_LIST_TEMP
    {
        public int GLT_ID { get; set; }
        public double GLT_PRICE { get; set; }
        public Nullable<int> GLT_STEAM_ID { get; set; }
        public Nullable<int> GLT_STEAM_BUNDLE_ID { get; set; }
        public string GLT_NAME { get; set; }
        public string GLT_IMAGE_PATH { get; set; }
        public string GLT_STEAM_REF { get; set; }
    }
}
