// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSteamParser.Models;

#nullable disable

namespace WebSteamParser.Migrations
{
    [DbContext(typeof(u1286676_STEAM_PARSINGContext))]
    [Migration("20220918171133_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("u1286676_Deallocate")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebSteamParser.Models.GameList", b =>
                {
                    b.Property<int>("GlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GlId"), 1L, 1);

                    b.Property<bool?>("GlAvailability")
                        .HasColumnType("bit")
                        .HasColumnName("GL_AVAILABILITY");

                    b.Property<string>("GlName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GL_NAME");

                    b.Property<double>("GlPrice")
                        .HasColumnType("float")
                        .HasColumnName("GL_PRICE");

                    b.Property<double?>("GlPriceKz")
                        .HasColumnType("float")
                        .HasColumnName("GL_PRICE_KZ");

                    b.Property<double?>("GlPriceRu")
                        .HasColumnType("float")
                        .HasColumnName("GL_PRICE_RU");

                    b.Property<double?>("GlPriceTr")
                        .HasColumnType("float")
                        .HasColumnName("GL_PRICE_TR");

                    b.Property<int?>("GlSteamId")
                        .HasColumnType("int")
                        .HasColumnName("GL_STEAM_ID");

                    b.HasKey("GlId")
                        .HasName("PK__GAME_LIS__E2DBDB9144DC3972");

                    b.ToTable("GAME_LIST", "dbo");
                });

            modelBuilder.Entity("WebSteamParser.Models.GameListTempKz", b =>
                {
                    b.Property<int>("GltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GLT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GltId"), 1L, 1);

                    b.Property<string>("GltImagePath")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("GLT_IMAGE_PATH");

                    b.Property<double?>("GltPrice")
                        .HasColumnType("float")
                        .HasColumnName("GLT_PRICE");

                    b.Property<int?>("GltSteamId")
                        .HasColumnType("int")
                        .HasColumnName("GLT_STEAM_ID");

                    b.ToTable("GAME_LIST_TEMP_KZ", "dbo");
                });

            modelBuilder.Entity("WebSteamParser.Models.GameListTempRu", b =>
                {
                    b.Property<int>("GltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GLT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GltId"), 1L, 1);

                    b.Property<string>("GltImagePath")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("GLT_IMAGE_PATH");

                    b.Property<double?>("GltPrice")
                        .HasColumnType("float")
                        .HasColumnName("GLT_PRICE");

                    b.Property<int?>("GltSteamId")
                        .HasColumnType("int")
                        .HasColumnName("GLT_STEAM_ID");

                    b.ToTable("GAME_LIST_TEMP_RU", "dbo");
                });

            modelBuilder.Entity("WebSteamParser.Models.GameListTempTr", b =>
                {
                    b.Property<int>("GltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GLT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GltId"), 1L, 1);

                    b.Property<string>("GltImagePath")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("GLT_IMAGE_PATH");

                    b.Property<double?>("GltPrice")
                        .HasColumnType("float")
                        .HasColumnName("GLT_PRICE");

                    b.Property<int?>("GltSteamId")
                        .HasColumnType("int")
                        .HasColumnName("GLT_STEAM_ID");

                    b.ToTable("GAME_LIST_TEMP_TR", "dbo");
                });

            modelBuilder.Entity("WebSteamParser.Models.GameListTempUsa", b =>
                {
                    b.Property<int>("GltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GLT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GltId"), 1L, 1);

                    b.Property<string>("GltImagePath")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("GLT_IMAGE_PATH");

                    b.Property<double?>("GltPrice")
                        .HasColumnType("float")
                        .HasColumnName("GLT_PRICE");

                    b.Property<int?>("GltSteamId")
                        .HasColumnType("int")
                        .HasColumnName("GLT_STEAM_ID");

                    b.HasKey("GltId")
                        .HasName("PK__GAME_LIS__EA70666574FF3FCD");

                    b.ToTable("GAME_LIST_TEMP_USA", "dbo");
                });

            modelBuilder.Entity("WebSteamParser.Models.OtherSiteList", b =>
                {
                    b.Property<int>("OslId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OSL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OslId"), 1L, 1);

                    b.Property<string>("OslName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("OSL_NAME");

                    b.Property<double?>("OslPrice")
                        .HasColumnType("float")
                        .HasColumnName("OSL_PRICE");

                    b.Property<string>("OslRef")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("OSL_REF");

                    b.Property<string>("OslSiteName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OSL_SITE_NAME");

                    b.Property<int?>("OslSteamId")
                        .HasColumnType("int")
                        .HasColumnName("OSL_STEAM_ID");

                    b.HasKey("OslId")
                        .HasName("PK__OTHER_SI__A46D1E121331F343");

                    b.ToTable("OTHER_SITE_LIST", "dbo");
                });

            modelBuilder.Entity("WebSteamParser.Models.UserFavorite", b =>
                {
                    b.Property<int>("UfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UF_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UfId"), 1L, 1);

                    b.Property<int?>("UfGlSteamId")
                        .HasColumnType("int")
                        .HasColumnName("UF_GL_STEAM_ID");

                    b.Property<int?>("UfUlId")
                        .HasColumnType("int")
                        .HasColumnName("UF_UL_ID");

                    b.HasKey("UfId")
                        .HasName("PK__USER_FAV__8FD45A596343B8CC");

                    b.ToTable("USER_FAVORITES", "dbo");
                });

            modelBuilder.Entity("WebSteamParser.Models.UserList", b =>
                {
                    b.Property<int>("UlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlId"), 1L, 1);

                    b.Property<double?>("UlBalance")
                        .HasColumnType("float")
                        .HasColumnName("UL_BALANCE");

                    b.Property<DateTime?>("UlLastVisit")
                        .HasColumnType("datetime")
                        .HasColumnName("UL_LAST_VISIT");

                    b.Property<string>("UlLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UL_LOGIN");

                    b.Property<string>("UlPassword")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UL_PASSWORD");

                    b.HasKey("UlId")
                        .HasName("PK__USER_LIS__FB8CA7AEF298C961");

                    b.ToTable("USER_LIST", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
